Repository ViacomInc/data-point, pull requests merged in 2018-02, with the labels that each got.

#207 feat(data-point): Refactor behavior of find, filter, and empty reducers
  packages/data-point/README.md
  packages/data-point/lib/entity-types/base-entity/resolve.js
  packages/data-point/lib/entity-types/base-entity/resolve.test.js
  packages/data-point/lib/entity-types/entity-collection/factory.js
  packages/data-point/lib/entity-types/entity-collection/factory.test.js
  packages/data-point/lib/entity-types/entity-collection/resolve.js
  packages/data-point/lib/entity-types/entity-collection/resolve.test.js
  packages/data-point/lib/entity-types/entity-hash/factory.js
  packages/data-point/lib/entity-types/entity-hash/factory.test.js
  packages/data-point/lib/entity-types/entity-hash/resolve.js
  packages/data-point/lib/entity-types/entity-hash/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-filter/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-filter/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-find/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-find/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-map/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-map/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-omit/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-omit/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-pick/resolve.js
  packages/data-point/lib/reducer-types/reducer-helpers/reducer-pick/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-helpers/utils/index.js
  packages/data-point/lib/reducer-types/reducer-helpers/utils/index.test.js
  packages/data-point/lib/reducer-types/reducer-list/factory.js
  packages/data-point/lib/reducer-types/reducer-list/resolve.js
  packages/data-point/lib/reducer-types/reducer-list/resolve.test.js
  packages/data-point/lib/reducer-types/reducer-object/__snapshots__/factory.test.js.snap
  packages/data-point/lib/reducer-types/reducer-object/factory.js
  packages/data-point/lib/reducer-types/reducer-object/resolve.js
  packages/data-point/lib/reducer-types/reducer-object/resolve.test.js
  packages/data-point/lib/utils/index.js
  packages/data-point/lib/utils/utils.test.js
Labels: adds breaking change

#217 Add Testing Style to Contributing docs
  CONTRIBUTING.md
Labels: type:documentation

#218 feat(data-point): Remove predefined hash and collection execution order
  packages/data-point-codemods/transforms/__testfixtures__/hash-and-collection-execution-order.input.js
  packages/data-point-codemods/transforms/__testfixtures__/hash-and-collection-execution-order.output.js
  packages/data-point-codemods/transforms/__tests__/hash-and-collection-execution-order-test.js
  packages/data-point-codemods/transforms/hash-and-collection-execution-order.js
  packages/data-point-codemods/transforms/utils.js
  packages/data-point/README.md
  packages/data-point/lib/entity-types/entity-collection/__snapshots__/factory.test.js.snap
  packages/data-point/lib/entity-types/entity-collection/factory.js
  packages/data-point/lib/entity-types/entity-collection/factory.test.js
  packages/data-point/lib/entity-types/entity-hash/__snapshots__/factory.test.js.snap
  packages/data-point/lib/entity-types/entity-hash/factory.js
  packages/data-point/lib/entity-types/parse-compose/__snapshots__/parse-compose.test.js.snap
  packages/data-point/lib/entity-types/parse-compose/parse-compose.js
  packages/data-point/lib/entity-types/parse-compose/parse-compose.test.js
  packages/data-point/lib/stores/__snapshots__/store-manager.test.js.snap
  packages/data-point/lib/stores/store-manager.test.js
  packages/data-point/test/definitions/hash.js
Labels: adds breaking change

#228 Use regex to split piped reducer-lists
  packages/data-point/lib/reducer-types/reducer-list/factory.js
  packages/data-point/lib/reducer-types/reducer-list/factory.test.js
Labels: type:refactor
