Repository ViacomInc/data-point, pull requests merged in 2019-09, with the labels that each got.

#412 docs(data-point): adds JSDoc across files
  packages/data-point/src/Accumulator.js
  packages/data-point/src/Reducer.js
  packages/data-point/src/ReducerObject.js
  packages/data-point/src/ReducerPath.js
  packages/data-point/src/create-reducer.js
  packages/data-point/src/is-plain-object.js
  packages/data-point/src/reducer-helpers/constant/constant.js
  packages/data-point/src/reducer-helpers/if-then-else/if-then-else.js
  packages/data-point/src/reducer-helpers/map/map.js
  packages/data-point/src/reducer-helpers/select/select.js
  packages/data-point/src/resolve.js
  packages/data-point/src/trace-span.js
Labels: canary 🚀

#406 feat(data-point): add tests for DataPoint module
  packages/data-point/src/Cache.js
  packages/data-point/src/Cache.test.js
  packages/data-point/src/DataPoint.js
  packages/data-point/src/DataPoint.test.js
  packages/data-point/src/data-point.js
  packages/data-point/src/index.js
Labels: canary 🚀

#417 feat(data-point): create tracing api
  documentation/docs/playground.js
  packages/data-point-tracer/index.js
  packages/data-point-tracer/package.json
  packages/data-point-tracer/src/Span.js
  packages/data-point-tracer/src/Tracer.js
  packages/data-point-tracer/src/reporters.js
  packages/data-point/package.json
  packages/data-point/src/DataPoint.js
  packages/data-point/src/DataPoint.test.js
  packages/data-point/src/ReducerEntity.js
  packages/data-point/src/ReducerEntity.test.js
  packages/data-point/src/resolve.js
  packages/data-point/src/resolve.test.js
  packages/data-point/src/trace-span.js
  packages/data-point/src/trace-span.test.js
  packages/data-point/src/tracing/Span.js
  packages/data-point/src/tracing/Span.test.js
  packages/data-point/src/tracing/Tracer.js
  packages/data-point/src/tracing/Tracer.test.js
  packages/data-point/src/tracing/trace-span.js
  packages/data-point/src/tracing/trace-span.test.js
Labels: canary 🚀

#418 feat(data-point): implement opentracing interface
  documentation/examples/opentracing/opentracing-example.js
  documentation/examples/opentracing/package.json
  packages/data-point-tracers/opentracing/index.js
  packages/data-point-tracers/opentracing/opentracing.js
  packages/data-point-tracers/opentracing/opentracing.test.js
  packages/data-point-tracers/package.json
Labels: canary 🚀

#420 feat(data-point-tracers): add mermaid support
  documentation/examples/mermaid-graph/mermaid-example.js
  documentation/examples/mermaid-graph/package.json
  packages/data-point-tracers/mermaid/index.js
  packages/data-point-tracers/mermaid/mermaid.js
  packages/data-point-tracers/mermaid/mermaid.test.js
Labels: canary 🚀

#424 build: update jest version and add jest types
  package.json
  yarn.lock
Labels: canary 🚀, upgrade versions

#427 ci: remove prettier-standard check
  .travis.yml
Labels: canary 🚀

#425 fix entity not passing error
  packages/data-point/src/ReducerEntity.js
  packages/data-point/src/ReducerEntity.test.js
Labels: canary 🚀, type:bug

#429 chore: update all package.json files
  .npmpackagejsonlintrc.json
  documentation/examples/mermaid-graph/package.json
  documentation/examples/opentracing/package.json
  documentation/website/package.json
  package.json
  packages/bench-trial/package.json
  packages/data-point-cache/package.json
  packages/data-point-express/package.json
  packages/data-point-service/package.json
  packages/data-point-tracers/LICENSE
  packages/data-point-tracers/README.md
  packages/data-point-tracers/package.json
  packages/data-point/package.json
  yarn.lock
Labels: canary 🚀

#430 Pretty pacakge json
  documentation/examples/mermaid-graph/package.json
  documentation/examples/opentracing/package.json
  documentation/website/package.json
  package.json
  packages/bench-trial/package.json
  packages/data-point-cache/package.json
  packages/data-point-express/package.json
  packages/data-point-service/package.json
  packages/data-point-tracers/package.json
  packages/data-point/package.json
  yarn.lock
Labels: canary 🚀

#431 docs(data-point): add @class tags
  documentation/docs/getting-started.md
  documentation/website/README.md
  documentation/website/jsdoc.json
  documentation/website/siteConfig.js
  documentation/website/static/img/favicon.ico
  packages/data-point/src/Accumulator.js
  packages/data-point/src/Cache.js
  packages/data-point/src/DataPoint.js
  packages/data-point/src/Reducer.js
  packages/data-point/src/ReducerEntity.js
  packages/data-point/src/ReducerFunction.js
  packages/data-point/src/ReducerList.js
  packages/data-point/src/ReducerNative.js
  packages/data-point/src/ReducerObject.js
  packages/data-point/src/ReducerPath.js
  packages/data-point/src/reducer-entities/model/model.js
  packages/data-point/src/reducer-helpers/assign/assign.js
  packages/data-point/src/reducer-helpers/constant/constant.js
  packages/data-point/src/reducer-helpers/if-then-else/if-then-else.js
  packages/data-point/src/reducer-helpers/map/map.js
  packages/data-point/src/reducer-helpers/parallel/parallel.js
  packages/data-point/src/reducer-helpers/select/select.js
  packages/data-point/src/tracing/Span.js
  packages/data-point/src/tracing/Tracer.js
Labels: canary 🚀

#428 fetch reducer
  documentation/docs/api/reducers/fetch.md
  documentation/website/i18n/en.json
  documentation/website/sidebars.json
  packages/data-point-fetch/Fetch.js
  packages/data-point-fetch/Fetch.test.js
  packages/data-point-fetch/LICENSE
  packages/data-point-fetch/README.md
  packages/data-point-fetch/index.js
  packages/data-point-fetch/package.json
  packages/data-point/Reducer.js
  packages/data-point/ReducerEntity.js
  packages/data-point/create-reducer.js
  packages/data-point/createReducer.js
Labels: canary 🚀

#438 fix(data-point-service): pass value to addEntry when revalidating
  packages/data-point-service/lib/cache-middleware.js
  packages/data-point-service/lib/cache-middleware.test.js
Labels: type:bug
